apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
spec:
  project: infra-app-project
  destination:
    namespace: metrics-server
    server: https://kubernetes.default.svc
  source:
    repoURL: https://kubernetes-sigs.github.io/metrics-server/
    targetRevision: 3.13.0
    chart: metrics-server
    helm:
      valuesObject:
