apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: infra-app-project
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  source:
    repoURL: https://charts.jetstack.io
    targetRevision: 1.16.5
    chart: cert-manager
    helm:
      valuesObject:
        crds:
          enabled: true