apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: myapp-external-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: myapp-creds-secret
  dataFrom:
    - extract:
        key: dev/mydjangoapp