---
apiVersion: v1
kind: Namespace
metadata:
  name: csi-driver-nfs

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-driver-nfs
  namespace: argocd
spec:
  project: default
  destination:
    namespace: csi-driver-nfs
    server: https://kubernetes.default.svc
  source:
    repoURL: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
    targetRevision: 4.11.0
    chart: csi-driver-nfs
    helm:
      valuesObject:
        storageClass:
          create: true
          name: nfs-csi
#          annotations:
#            storageclass.kubernetes.io/is-default-class: "true"
          parameters:
            server: 10.0.0.107
            share: /srv/nfs_share
            subDir:
            mountPermissions: "0777"
#            csi.storage.k8s.io/provisioner-secret is only needed for providing mountOptions in DeleteVolume
#            csi.storage.k8s.io/provisioner-secret-name: "mount-options"
#            csi.storage.k8s.io/provisioner-secret-namespace: "default"
          reclaimPolicy: Delete
          volumeBindingMode: Immediate
          mountOptions:
            - nfsvers=4.1
        volumeSnapshotClass:
          create: true
          name: csi-nfs-snapclass
          deletionPolicy: Delete
        externalSnapshotter:
          enabled: true
          name: snapshot-controller
          priorityClassName: system-cluster-critical
          deletionPolicy: Delete
          controller:
            replicas: 1
          resources:
            limits:
              memory: 300Mi
            requests:
              cpu: 10m
              memory: 20Mi
          # Create volume snapshot CRDs.
          customResourceDefinitions:
            enabled: true
        feature:
          enableFSGroupPolicy: true     # creates/patches the CSIDriver object
        controller:
          driver:
            fsGroupPolicy: None         # prevent kubelet recursive chgrp on NFS
